- id: arxiv:2504.17461
  publisher: 10th International Conference on Smart and Sustainable Technologies
- id: url:https://www.researchgate.net/profile/Sergey-Yurish/publication/390831248_Artificial_Intelligence_in_Medicine_and_Healthcare_Proceedings_of_the_1st_International_Conference_on_AI_in_Medicine_and_Healthcare_AiMH'_2025_8-10_April_2025_Innsbruck_Austria/links/67ff7dcad1054b0207d4b4b5/Artificial-Intelligence-in-Medicine-and-Healthcare-Proceedings-of-the-1st-International-Conference-on-AI-in-Medicine-and-Healthcare-AiMH-2025-8-10-April-2025-Innsbruck-Austria.pdf#page=99
  publisher: International Conference on AI in Medicine and Healthcare (AiMH' 2025)
- id: arxiv:2504.03736
  publisher: 3rd World Conference on eXplainable Artificial Intelligence (XAI-2025)
- id: arXiv:2409.17157
  publisher: AIMLAI Workshop, ECML 2024, Vilnius
- id: arXiv:2409.03887
- id: arXiv:2408.11619
  publisher: Workshop on Public Interest AI at 47th German Conference on AI (KI 2024)
- id: arXiv:2407.21453
  publisher: IEEE International Symposium on the Internet of Sounds, Erlangen
- id: arxiv:2409.01138
  publisher: Workshop on Public Interest AI at 47th German Conference on AI (KI 2024)
- id: doi:10.1007/s11023-024-09663-3
- id: url:https://proceedings.mlr.press/v238/jager24a
- id: url:https://ojs.weizenbaum-institut.de/index.php/wjds/article/view/4_1_2/124
- id: arxiv:2404.18504
  date: 2023-01-01
  publisher: Remote Sensing for Agriculture, Ecosystems, and Hydrology XXV
- id: doi:10.14512/OEW380346
- id: doi:10.1016/j.ejrad.2023.110964
- id: url:https://link.springer.com/chapter/10.1007/978-3-658-39302-1_21
  publisher: World Conference on Explainable Artificial Intelligence
- id: doi:10.1148/radiol.222276
- id: arXiv:2404.11461
  date: 2023-01-01
  publisher: Annual Meeting of the Institute of Nuclear Materials Management (INMM), Vienna
- id: arXiv:2404.07754
  date: 2023-01-01
  publisher: Annual Meeting of the Institute of Nuclear Materials Management (INMM), Vienna
- id: arXiv:2204.10416 
  publisher: Pervasive and Mobile Computing
- id: doi:10.1016/j.procs.2024.05.091
  date: 2023-01-01
- id: arxiv:2308.04444
  date: 2022-01-01
  publisher: International Conference on Social Informatics
- id: arxiv:2207.10733
  publisher: DataPerf Workshop at the 39 th International Conference on Machine Learning, Baltimore, Maryland, USA
- id: arxiv:2206.07497
  publisher: Presented at XAI4CV Workshop at CVPR
- id: doi:10.3389/frsus.2022.922984
- id: arXiv:2205.02908
- id: doi:10.1145/3487553.3524218
- id: arXiv:2112.12444
- id: doi:10.3389/fdata.2021.693674
- id: arXiv:2106.11394
  publisher: Proceedings of the ICML Workshop on Theoretical Foundations, Criticism, and Application Trends of Explainable AI held in conjunction with the 38th International Conference on Machine Learning (ICML)
- id: arXiv:2107.02033
  publisher: Proceedings of the ICML Workshop on Theoretical Foundations, Criticism, and Application Trends of Explainable AI held in conjunction with the 38th International Conference on Machine Learning (ICML)
- id: doi:10.1145/3448016.3457295
- id: url:https://www.amazon.science/publications/automated-data-validation-in-machine-learning-systems
  publisher: IEEE Data Engineering Bulletin
- id: doi:10.1145/3430524.3442451
- id: arXiv:2407.05788
  date: 2021-05-01
  publisher: ECML/PKDD Workshop on Automating Data Science
- id: url:https://www.amazon.science/publications/jenga-a-framework-to-study-the-impact-of-data-errors-on-the-predictions-of-machine-learning-models
  publisher: 24th International Conference on Extending Database Technology (EDBT)
- id: doi:10.1080/12460125.2020.1819094
- id: doi:10.1109/EMBC44109.2020.9176083
- id: doi:10.1145/3318464.3380604
- id: arxiv:2006.08368
- id: url:https://link.springer.com/chapter/10.1007/978-3-030-57321-8_24
  publisher: International Cross-Domain Conference for Machine Learning and Knowledge Extraction
- id: url:https://www.amazon.science/publications/towards-automated-data-quality-management-for-machine-learning
  publisher: MLSys 2020 Workshop on MLOps Systems

